---
driver                    :
    name                  : docker
    socket                : unix:///var/run/docker.sock
    use_sudo              : false

provisioner:
    name                  : ansible_push
    verbose               : "vvvv"
    chef_bootstrap_url    : nil
    ansible_config        : "test/ansible.cfg"
    idempotency_test      : True
    diff                  : True

verifier:
  name: serverspec
  remote_exec             : false
  default_pattern         : true


platforms:
 - name                   : ubuntu1604
   driver_config          :
     image                : ubuntu:xenial
     platform             : ubuntu
     provision_command     : echo "kitchen:$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)" | sudo chpasswd


   provisioner            :
     ansible_playbook_bin : "$(avm path v2.0)ansible-playbook"

suites                    :

  - name                  : ghrelease
    provisioner           :
        playbook          : "test/integration/ghrelease/source.yml"

  - name                  : user
    provisioner           :
        playbook          : "test/integration/user/user.yml"

  - name                  : directory
    provisioner           :
        playbook          : "test/integration/directory/directory.yml"

  - name                  : resolver_git
    provisioner           :
        playbook          : "test/integration/resolver_git/resolver_git.yml"

  - name                  : resolver_s3_hash
    provisioner           :
        playbook          : "test/integration/resolver_s3_hash/resolver_s3_hash.yml"

  - name                  : resolver_s3_file
    provisioner           :
        playbook          : "test/integration/resolver_s3_file/resolver_s3_file.yml"

  - name                  : delete_old_deployment
    provisioner           :
        playbook          : "test/integration/delete_old_deployment/delete_old_deployment.yml"

  - name                  : fastcgi_parm
    provisioner           :
        playbook          : "test/integration/fastcgi_parm/fastcgi_parm.yml"

  - name                  : shell_vars
    provisioner           :
        playbook          : "test/integration/shell_vars/shell_vars.yml"

  - name                  : custom_config
    provisioner           :
        playbook          : "test/integration/custom_config/custom_config.yml"

  - name                  : dotenv
    provisioner           :
        playbook          : "test/integration/dotenv/dotenv.yml"

  - name                  : yaml_vars
    provisioner           :
        playbook          : "test/integration/yaml_vars/yaml_vars.yml"
