---

- name: config | fastcgi_parm | write fastcgi parm multi variable files
  hf_env_vars: 
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="{{ deployment_config_file_perm }}"
    vars="{{ deployment_config_fastcgi_parm_vars }}"
    template="{{ deployment_config_fastcgi_parm_vars_template }}"
  when: "deployment_config_fastcgi_parm_vars is not mapping"
  notify:
     - restart app
