---

- name: config | php_pool_parm | write php pool parm multi variable files
  hf_env_vars: 
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="{{ deployment_config_file_perm }}"
    vars="{{ deployment_config_php_pool_parm_vars }}"
    template="{{ deployment_config_php_pool_parm_vars_template }}"
    add_ansible_header=False
  when: "deployment_config_php_pool_parm_vars is not mapping"
  notify:
     - restart app
