---

- name: config | environment_variable | write environment variables to a multi files
  hf_env_vars: 
    owner="{{ deployment_user }}"
    group="{{ deployment_group }}"
    mode="{{ deployment_config_file_perm }}"
    vars="{{ deployment_config_shell_vars }}"
    template="{{ deployment_config_shell_vars_template }}"
  when: "deployment_config_shell_vars is not mapping"
  notify:
     - restart app